addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libssl-dev
      - gcc-4.9-multilib
      - g++-4.9-multilib
after_success:
  - npm run coveralls
before_install:
  - export GYP_DEFINES="coverage=0 use_obsolete_asm=true";
  - export CC=/usr/bin/gcc-4.9;
  - export CXX=/usr/bin/g++-4.9;
  - git config --global user.name travis
  - git config --global user.email travis@locahost
install:
  - npm install
language: node_js
node_js:
  - '4'
  - '6'
  - 'stable'
os:
  - linux
sudo: false
