addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libssl-dev
      - gcc-4.9-multilib
      - g++-4.9-multilib
language: node_js
node_js:
  - '6'
  - '8'
  - '10'
os:
  - linux
  - osx
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - git config --global user.name travis
  - git config --global user.email travis@locahost
install:
  - travis_retry npm install
script:
  - npm run codecov
