version: 2.0

jobs:
  "node-8":
    docker:
      - image: circleci/node:8
    working_directory: ~/nodegit-kit-8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt install build-essential libssl-dev gcc-4.9-multilib g++-4.9-multilib
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: git config --global user.name travis
      - run: git config --global user.email travis@locahost
      - run:
          name: Run tests
          command: npm test

  "node-10":
    docker:
      - image: circleci/node:10
    working_directory: ~/nodegit-kit-10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt install build-essential libssl-dev gcc-4.9-multilib g++-4.9-multilib
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: git config --global user.name travis
      - run: git config --global user.email travis@locahost
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - "node-8"
      - "node-10"
