version: 2.0

jobs:
  "node-12":
    docker:
      - image: circleci/node:12-jessie
    working_directory: ~/nodegit-kit-12
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: git config --global user.name travis
      - run: git config --global user.email travis@locahost
      - run:
          name: Run tests
          command: npm test

  "node-10":
    docker:
      - image: circleci/node:10-jessie
    working_directory: ~/nodegit-kit-10
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: git config --global user.name travis
      - run: git config --global user.email travis@locahost
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - "node-12"
      - "node-10"
